name: Fetch latest version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run build
      - name: Check Changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
      - run: printf "package_version=%s" "$(npm version patch --no-git-tab-version)" >> $GITHUB_OUTPUT
        if: steps.changes.outputs.changed == 1
        id: bump
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.changes.outputs.changed == 1
        with:
          tagging_message: ${{ steps.bump.outputs.package_version }}
